### ISSUE TITLE
labkey.executeSql breaks when using the containerFilter option

### ISSUE THREAD

**Issue by lakikowolfe** [LabKey/labkey-api-r#18]
Here's the code I'm running:
```r
library(Rlabkey)
labkey.url.base <- "https://test.immunespace.org"
labkey.url.path <- "/Studies/"
sql <- "SELECT * FROM containers"
result <- labkey.executeSql(
  baseUrl = labkey.url.base,
  folderPath = labkey.url.path,
  schemaName = "core",
  sql = sql,
  containerFilter = "Current")
```

This is the error I get:
```
Error: lexical error: invalid char in json text.
                                       <!doctype html><html lang="en">
                     (right here) ------^
```

Seems to be due to pasting the parameters instead of concatenating them. Could you take a look?

**Comment by juyeongkim** [comment]
@lakikowolfe is referring to this line specifically: https://github.com/LabKey/labkey-api-r/blob/develop/Rlabkey/R/labkey.executeSql.R#L47

**Comment by cnathe** [comment]
@lakikowolfe  A fix for this issue has been checked in to the fb_domain_33287 branch. It should likely be merged to develop and the updated Rlabkey version posted to CRAN next week, but let me know if you'd like a copy of the updated package before that.
