### ISSUE TITLE
Rlabkey can't retrieve data from group-concatenated columns

### ISSUE THREAD

**Issue by juyeongkim** [LabKey/labkey-api-r#27]
I am trying to retrieve data from a sql query, but the `Rlabkey` functions return no data for group-concatenated columns via `GROUP_CONCAT`.

## Minimal reproducible example

``` r
dataset <- Rlabkey::labkey.executeSql(
  baseUrl = "https://myawesomelabkey.com", 
  folderPath = "", 
  schemaName = "auditLog",
  sql = "
  SELECT
  CAST(UserAuditEvent.Created AS DATE) as date,
  COUNT(distinct UserAuditEvent.CreatedBy) as n_users,
  GROUP_CONCAT(distinct UserAuditEvent.CreatedBy, '; ') as users
  FROM UserAuditEvent
  WHERE
  UserAuditEvent.comment LIKE '%logged in successfully via Database authentication.'
  GROUP BY CAST(UserAuditEvent.Created AS DATE)
  "
)
# check if we are fetching the sql query
dim(dataset)
#> [1] 1360    3

# check if we are retrieving any data in users column (group_concat)
all(is.na(dataset$Users))
#> [1] TRUE
```

<sup>Created on 2019-02-08 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

NOTE: I tried this sql query in the labkey UI, and it works and returns concatenated data from `users` columns. I was also able to retrieve data from this query via javascript API.

**Comment by cnathe** [comment]
Sorry for the delay on this. I believe I have a local fix. I am running it through the test framework to verify. I will get an updated Rlabkey package posted (likely tomorrow) for you to try out.
Thanks,
Cory

**Comment by juyeongkim** [comment]
Thanks @cnathe!
