### ISSUE TITLE
labkey.selectRows should alert users to invalid column names in filter

### ISSUE THREAD

**Issue by jmtaylor-fhcrc** [LabKey/labkey-api-r#44]
Passing a filter to `labkey.selectRows` with an invalid column name
ignores the column rather than throwing an error or a warning.

This is behavior could cause issues in an analysis when small typos are
made in column names.

The `labkey.selectRows` function does throw a warning when an empty
table is returned. There should be a similar behavior when invalid
columns are passed.

4 filters:

1. NULL returns all data
2. filters a field that exists with a value that exists
3. filters a field that exists with a value that does not exist
4. filters a field that does not exist with a value that does exist
5. filters a field that does not exist with a value that does not exist

```
colFilter <- list(
  NULL,
  Rlabkey::makeFilter(c("antibody_isotype", "EQUALS", "IgG")),
  Rlabkey::makeFilter(c("antibody_isotype", "EQUALS", "IgX")),
  Rlabkey::makeFilter(c("antibody_isERROR", "EQUALS", "IgG")),
  Rlabkey::makeFilter(c("antibody_isERROR", "EQUALS", "IgX"))
)

getData <- function(colFilter){
  Rlabkey::labkey.selectRows(
    baseUrl = "https://dataspace.cavd.org",
    folderPath = "/CAVD/vtn505",
    schemaName = "study",
    queryName = "BAMA",
    viewName = NULL,
    colNameOpt = "fieldname",
    colFilter = colFilter,
    method = "GET"
  )
}

results <- lapply(colFilter, getData)
lapply(results, nrow)
```
returns...
```
[[1]]
[1] 10260

[[2]]
[1] 3393

[[3]]
[1] 0

[[4]]
[1] 10260

[[5]]
[1] 10260
```

**Comment by labkey-bpatel** [comment]
LabKey issue now created: https://www.labkey.org/home/Developer/issues/issues-details.view?issueId=39288
