### ISSUE TITLE
Suggested doc addition

### ISSUE THREAD

**Issue by bbimber** [LabKey/labkey-api-r#67]
Hello,

I figured out a fix that might be useful to document. One can do this:

Rlabkey::labkey.setCurlOptions(NETRC_FILE = '/users/Bimber/Documents/_netrc2')

to provide an alternate location for .netrc. We found this useful (essential) to get a dockerized form of this working. This too some reading to figure out, so it might be worth a simple mention in your docs.

**Comment by labkey-adam** [comment]
Thanks, @bbimber : Good tip, I'll pass this along to the docs team.

**Comment by cnathe** [comment]
Agreed, this would be helpful to document. I'll get it added to the Rlabkey package docs page for labkey.setCurlOptions.

**Comment by cnathe** [comment]
Added here: https://github.com/LabKey/labkey-api-r/pull/68/commits/027b7467abb1559253d640307245ea820a9c4a3a
I will close this issue once that related PR is merged to develop.

**Comment by cnathe** [comment]
This doc update was merged to develop and will be in Rlabkey version 2.7.0
